### ISSUE TITLE
Merging lists

### ISSUE THREAD

**Issue by smob123** [GroceriStar/onboarding-features#19]
@atherdon 

https://github.com/GroceriStar/onboarding-features/blob/c6d163d7f0542a811550b2436ded2b29820fac44/src/components/Calendar.js#L16-L35

This code is responsible for merging lists, and then looping through the generated list to return months..

https://github.com/GroceriStar/onboarding-features/blob/c6d163d7f0542a811550b2436ded2b29820fac44/src/components/Calendar.js#L42-L64

This part is to loop through the days, and add numbers bellow each day

https://github.com/GroceriStar/onboarding-features/blob/c6d163d7f0542a811550b2436ded2b29820fac44/src/components/Features.js#L7-L10

and this one is to handle the duplicate functionalities in the html template

**Comment by atherdon** [comment]
reply at #5
