### ISSUE TITLE
help me with a similar task

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/onboarding-features#20]
So please check codebase of this repo.
it can be a bit confusing, but it's a still react inside.

https://github.com/atherdon/bebe-grocery
and tell me how it can be improved

#5

**Comment by atherdon** [comment]
just pushed the latest updates. just to let you know,

1) **banner.js** it's just for animation purposes. so when you click on that button - it's scrolls to first section of the homepage.
2) **menu.js** i think it's just an empty link
3) i like that you mention to change the component file name.
4) let's change the title - what do you can purpose?
5) like `<p><strong></strong></p>` - not sure if i agree, i think that both of this tags are outdated. i mean it's better to use articles or divs with styles. but this another free template, so ...

6) yeah i just making this real quick, and lazy to change that.

also please find out that i tried to create a data files too. so it'll be cool if you checkout the current version and make some changes. can you do that?

**Comment by smob123** [comment]
Just pushed the changes, sorry I got a little busy today that is why I did not do it until now

**Comment by smob123** [comment]
> let's change the title - what do you can purpose?
Maybe you can say something like "Here is how our app can help you"

> like <p><strong></strong></p> - not sure if i agree, i think that both of this tags are outdated. i mean it's better to use articles or divs with styles. but this another free template, so ...

I did not know that it was outdated, I suggested using them because this is how my prof taught me.

> also please find out that i tried to create a data files too. so it'll be cool if you checkout the current version and make some changes. can you do that?

was there a specific file you wanted me to look at?

**Comment by atherdon** [comment]
it's ok, don't worry about it. i mean there no rush at all. so if you need
some time - just take it. i this it's important to know that freedom is
more important than just make things done in time. especially with such
complex work as software development...


On 01-May-2018 at 09:05 PM, smob123 wrote:


Just pushed the changes, sorry I got a little busy today that is why I did
not do it until now

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/onboarding-features/issues/20#issuecomment-385790109>,
or mute the thread

**Comment by atherdon** [comment]
and i like your suggestion/ i always stuck with content like this

**Comment by smob123** [comment]
Just pushed the changes I suggested, the only thing that may break the code is that I changed BottomChangeThis.js to Bottom.js

**Comment by smob123** [comment]
Actually, never mind, I received an error because I do not have permission  to push into the repo

**Comment by atherdon** [comment]
@smob123 can you fork that repo - apply your changes and one a pull request at main repository? i think it'll work

**Comment by smob123** [comment]
Okay, it is up now

**Comment by atherdon** [comment]
i didn't see your pull request

**Comment by atherdon** [comment]
still not clear. do you put your code changes at your forked repo? if yes, you need to open a pull request in order to have ability to merge your code changes with my code.
check this: https://yangsu.github.io/pull-request-tutorial/

**Comment by smob123** [comment]
I just did that, but there seems to be some sort of an error related to halmet that is preventing checks

**Comment by atherdon** [comment]
not a problem.
btw, i assume you should commit some files, because 
> that I changed BottomChangeThis.js to Bottom.js

i didn't see that

**Comment by smob123** [comment]
That's odd, because the file is on the forked repo I have

![capture](https://user-images.githubusercontent.com/26127333/39555399-781db64a-4e4f-11e8-859b-813cacd36a45.PNG)

**Comment by atherdon** [comment]
try `git add *`

**Comment by smob123** [comment]
I just retried it, but nothing was added, it says that working tree is clean

**Comment by atherdon** [comment]
delete that file and then add it again


On 03-May-2018 at 01:37 AM, smob123 wrote:


I just retried it, but nothing was added, it says that working tree is clean

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/onboarding-features/issues/20#issuecomment-386170257>,
or mute the thread

**Comment by smob123** [comment]
Is it up now?

**Comment by atherdon** [comment]
yep, it works well
